import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
//import NoticeMenu from '@/ui/Navbar/NoticeMenu';
import AppNavbar from '@/ui/Navbar/AppNavbar';
import AdminMenu from '@/ui/Navbar/AdminMenu';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" className='flex flex-col min-h-dvh'>
        <body className={`${inter.className} flex flex-col grow`}>
          <Toaster />
          <AdminMenu />
          {/* <NoticeMenu /> */}
          <AppNavbar />
          <main className='flex flex-col grow'>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  )
}
